### ISSUE TITLE
wx.TextEntryDialog(): arguments did not match any overload call

### ISSUE THREAD

**Issue by JasonTraud** [md100play/HP3457A-GPIB#1]
I am receiving the following error when attempting to run dmm_control.py after installing the latest release of wxPython. 

Is there a specific version that needs to be used?

C:\Users\Jason\Downloads\HP3457A-GPIB-master\HP3457A-GPIB-master>python dmm_control.py
Traceback (most recent call last):
  File "dmm_control.py", line 727, in <module>
    app.frame = GraphFrame()
  File "dmm_control.py", line 223, in __init__
    self.setCom(None)
  File "dmm_control.py", line 622, in setCom
    dlg = wx.TextEntryDialog(self, "What is the serial port?", defaultValue="COM1")
TypeError: TextEntryDialog(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: 'defaultValue' is not a valid keyword argument

**Comment by MikeDombo** [comment]
I wrote it for use with wxpython 3, I think. Looking at the updated documentation for wxpython, I would suggest removing "defaultValue=" and just pass "COM1" as the third parameter.

Let  me know if that helps. 

If it doesn't work, you can try an earlier version of wxpython.

**Comment by JasonTraud** [comment]
Thanks! That seems working now. Any help on getting the DMM to show up as a COM port? I'm using a USB to GPIB adapter from Agilent and it's showing up as a GPIB device. Do I need to use a USB to RS232  to connect to the instrument? Or is there a different USB to GPIB adapter you're using?

**Comment by MikeDombo** [comment]
I am using a USB GPIB adapter from [Galvant.ca](http://www.galvant.ca/#!/store/gpibusb) which appears to the computer as a serial device. To use my interface you will need the multimeter to show up as a serial device because I use a python serial library for talking to the dmm. If you can program, I'm sure there is some library out there to directly talk to the dmm over gpib without serial, but I don't have such a device to test with.
